name: bluetooth_x_print
description: X Printer Integration with Flutter
version: 1.0.1
homepage: https://github.com/e3m-software/bluetooth_x_print

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.0.1
  rxdart: ^0.27.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.5
  json_serializable: ^4.1.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.bluetooth_x_print
        pluginClass: BluetoothPrintPlugin
      ios:
        pluginClass: BluetoothPrintPlugin
